package models

// SSH phase constants for the tunnel migration/lockdown lifecycle.
const (
	SSHPhasePublic             = "public"
	SSHPhaseDualListenPending  = "dual_listen_pending"
	SSHPhaseDualListenVerified = "dual_listen_verified"
	SSHPhaseTunnelOnlyPending  = "tunnel_only_pending"
	SSHPhaseTunnelOnlyVerified = "tunnel_only_verified"
	SSHPhaseError              = "error"
)

// SSHIsMigrated returns true if SSH has been moved to the tunnel (any phase past public).
func (t *SiteTunnel) SSHIsMigrated() bool {
	switch t.SSHPhase {
	case SSHPhaseDualListenPending, SSHPhaseDualListenVerified,
		SSHPhaseTunnelOnlyPending, SSHPhaseTunnelOnlyVerified:
		return true
	}
	return false
}

// SSHIsLockedDown returns true if public SSH has been removed.
func (t *SiteTunnel) SSHIsLockedDown() bool {
	return t.SSHPhase == SSHPhaseTunnelOnlyPending || t.SSHPhase == SSHPhaseTunnelOnlyVerified
}

// SiteTunnel represents a WireGuard site-to-site tunnel between the local
// OPNsense firewall and a remote Linux endpoint (VPS).
type SiteTunnel struct {
	ID         int64 `json:"id"`
	InstanceID int64 `json:"-"` // FK to firewall_instances

	// Identity
	Name        string `json:"name" binding:"required"`
	Description string `json:"description"`

	// Remote SSH access
	RemoteHost    string `json:"remote_host" binding:"required"` // IP or hostname
	SSHPort       int    `json:"ssh_port"`                       // default 22
	SSHUser       string `json:"ssh_user"`                       // default root
	SSHPrivateKey string `json:"ssh_private_key"`                // PEM-encoded key contents
	SSHPassword   string `json:"ssh_password"`                   // fallback if no key

	// Tunnel addressing
	TunnelSubnet string `json:"tunnel_subnet"` // e.g. "10.200.200.0/24"
	FirewallIP   string `json:"firewall_ip"`   // e.g. "10.200.200.2"
	RemoteIP     string `json:"remote_ip"`     // e.g. "10.200.200.1"
	ListenPort   int    `json:"listen_port"`   // WG listen port on remote, default 51820
	Keepalive    int    `json:"keepalive"`     // PersistentKeepalive, default 25

	// WireGuard keys (generated by Gator)
	FirewallPrivateKey string `json:"-"`
	FirewallPublicKey  string `json:"firewall_public_key"`
	RemotePrivateKey   string `json:"-"`
	RemotePublicKey    string `json:"remote_public_key"`

	// Remote WireGuard interface name (e.g. "wg0", "wg1")
	RemoteWGInterface string `json:"remote_wg_interface"`

	// OPNsense resource UUIDs (set during deploy)
	OPNsensePeerUUID   string `json:"-"`
	OPNsenseServerUUID string `json:"-"`

	// SSH hardening state.
	// SSHPhase tracks where we are in the migration/lockdown lifecycle:
	//   "public"                — default, SSH via public IP
	//   "dual_listen_pending"   — migration in progress, not yet verified
	//   "dual_listen_verified"  — migrated + verified via new tunnel connection
	//   "tunnel_only_pending"   — lockdown in progress, not yet verified
	//   "tunnel_only_verified"  — locked down + verified
	//   "error"                 — something failed, needs manual attention
	SSHPhase           string `json:"-"`
	OriginalRemoteHost string `json:"-"`
	OriginalSSHPort    int    `json:"-"`
	SSHSocketWasActive bool   `json:"-"` // was ssh.socket active before we disabled it?
	UFWWasActive       bool   `json:"-"` // was ufw active before lockdown enabled it?

	// Status
	Deployed bool   `json:"deployed"`
	Status   string `json:"status"` // "pending", "deployed", "error"

	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// SiteTunnelStatus is the API response for tunnel listings.
type SiteTunnelStatus struct {
	ID                int64  `json:"id"`
	Name              string `json:"name"`
	Description       string `json:"description"`
	RemoteHost        string `json:"remote_host"`
	TunnelSubnet      string `json:"tunnel_subnet"`
	FirewallIP        string `json:"firewall_ip"`
	RemoteIP          string `json:"remote_ip"`
	ListenPort        int    `json:"listen_port"`
	RemoteWGInterface string `json:"remote_wg_interface"`
	Deployed          bool   `json:"deployed"`
	Status            string `json:"status"`

	// Live status (populated by status check, not stored)
	Handshake       string `json:"handshake,omitempty"`   // last handshake time
	TransferRx      string `json:"transfer_rx,omitempty"` // bytes received
	TransferTx      string `json:"transfer_tx,omitempty"` // bytes sent
	RemoteReachable bool   `json:"remote_reachable"`

	CreatedAt string `json:"created_at"`
}

// SiteTunnelDetail is the full detail response including sensitive fields.
type SiteTunnelDetail struct {
	SiteTunnelStatus
	SSHPort           int    `json:"ssh_port"`
	SSHUser           string `json:"ssh_user"`
	HasSSHKey         bool   `json:"has_ssh_key"`
	HasSSHPassword    bool   `json:"has_ssh_password"`
	FirewallPublicKey string `json:"firewall_public_key,omitempty"`
	RemotePublicKey   string `json:"remote_public_key,omitempty"`
	Keepalive         int    `json:"keepalive"`
}
